# CODING GPT FROM SCRATCH

This Notebook follows [Code GPT From Scratch](https://www.youtube.com/watch?v=kCc8FmEb1nY), by Andrej Karpathy. This is my implementation, with my explanations, to better understand the way transformers work. 

The goal of this notebook is to implement a ***G***enrative ***P***retrained ***T***ransformer ***(GPT)***, that will generate Shakespeare like text.

## 1. Preparing the Dataset
In this projects, we are going to use [Tiny Shakespeare Dataset](https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt).

To prepare the dataset for processing, 

1. Download shakespeare data
2. Create tokenizer - what are the distinct charerchters we have?
3. create the enconder -> charecter to int
   create the decoder -> int back to charerechter.
4. show the first 1000 tokens in the dataset.
5. define block size
   define batch size
6. set the torch.seed to 1337 torch.seed(1037)
7. split to 90%-10% train/val
8. randomly sample the data.
   Create the batch size
   
   
 1. The initial loss should be that of a uniformal random variables:
    loss_i = -ln(1/65) [65 charecters/tokens] 

### 1.1 Download the data

In [1]:
#!wget(https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt)
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

### 1.2 Build the Tokenizer, Encoder and Decoder
Our goal is to have the ability to convert a string of text, into a sequence of integers, and back.
To do this, we first need to create a tokenizer, that will map each character to an integer. This is done by going over the entire dataset, and building the vocabulary: the set of all unique characters in the dataset.

After that, we will create the encoder - that maps a string of text into a sequence of numbers, and the decoder - that maps a sequence of numbers bak to a string of text.

In [2]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print('Vocabulary size (num of unique chars):', vocab_size)

# create a mapping from character to index and vice versa
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}

# create the encoder (ch -> idx) and decoder (idx -> ch) functions
encode = lambda s: [stoi[c] for c in s] #encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) #decoder: take a list of integers, output a string

print(encode("hi there"))
print (decode(encode("hi there")))

Vocabulary size (num of unique chars): 65
[46, 47, 1, 58, 46, 43, 56, 43]
hi there


### 1.3 Train and Test Split

In [3]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:128: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [4]:

data = torch.tensor(encode(text), dtype=torch.long)
n = int(len(data)*0.9)
train_data, val_data = data[:n], data[n:]

# lets print the first 200 elements of data. This is what our data looks like.
print(data[:200])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59])


## 2. Feeding Data Into The Network

We will never feed the entire dataset into the network. Instead we feed it with a sequence, up to a fixed block size. 

### 2.1. The Idea of Input `Context`, and `Block_Size` 
We are going to be using `B-Gram Model`: A very simple model, that predicts the `next 1 word` based on a given sequence. The input sequence is called the `context`. The maximum length `context`us called `block_size`. We want the model predict the next word, given `context` of length `[1..block_size]`. Later on, this will be usefull for the transformer network to predict sequences of any given length up to `block_size`

In [5]:
block_size = 8
print(train_data[:block_size+1])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])


In [6]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
print(f"The input tensor is: {x}")
print(f"The target tensor is: {y}")
print("So that...")
for t in range(block_size):
    context = x[:t+1]
    target =  y[t]
    print(f"For input {context}, the output is: {target}")

The input tensor is: tensor([18, 47, 56, 57, 58,  1, 15, 47])
The target tensor is: tensor([47, 56, 57, 58,  1, 15, 47, 58])
So that...
For input tensor([18]), the output is: 47
For input tensor([18, 47]), the output is: 56
For input tensor([18, 47, 56]), the output is: 57
For input tensor([18, 47, 56, 57]), the output is: 58
For input tensor([18, 47, 56, 57, 58]), the output is: 1
For input tensor([18, 47, 56, 57, 58,  1]), the output is: 15
For input tensor([18, 47, 56, 57, 58,  1, 15]), the output is: 47
For input tensor([18, 47, 56, 57, 58,  1, 15, 47]), the output is: 58


## 2.2. Processing Input Batch

When `context` size is `[1,...,block_size]`; `block_size=8` We have `8` different input contexts, with corresponding `8` different output targets. In other words, `8` training examples. To improve training speed, we will be adding the `batch` dimension. We will be randomly sampling `batch_size` samples from the training data, and use them for training.

In [7]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split=='train' else val_data
    # Sample batch_size random samples from data
    ix = torch.randint(len(data) - block_size, (batch_size, ))
    x = torch.stack([data[i:i+block_size] for i in ix]).to(device)
    y = torch.stack([data[i+1: i+ 1 + block_size] for i in ix]).to(device)
    
    return x, y

In [8]:
xb, yb = get_batch(split="train")

print("input batch:")
print(f"shape: {xb.shape}")
print(xb)

print("target batch:")
print(f"shape: {yb.shape}")
print(yb)

input batch:
shape: torch.Size([4, 8])
tensor([[56,  6,  0, 24, 43, 58,  1, 61],
        [39, 47, 51,  1, 58, 46, 39, 58],
        [52, 45,  1, 58, 53,  1, 57, 39],
        [43, 47, 52, 45,  1, 46, 53, 50]])
target batch:
shape: torch.Size([4, 8])
tensor([[ 6,  0, 24, 43, 58,  1, 61, 46],
        [47, 51,  1, 58, 46, 39, 58,  1],
        [45,  1, 58, 53,  1, 57, 39, 63],
        [47, 52, 45,  1, 46, 53, 50, 47]])


There are 4 batches. 
Each batch has 8 different contexts (`1,..,block_size`).
There are 8*4=32 different input-target pairs in every batch.

In [9]:
for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"For input tensor: {context}, the target is: {target}")
    print ("-----")

For input tensor: tensor([56]), the target is: 6
For input tensor: tensor([56,  6]), the target is: 0
For input tensor: tensor([56,  6,  0]), the target is: 24
For input tensor: tensor([56,  6,  0, 24]), the target is: 43
For input tensor: tensor([56,  6,  0, 24, 43]), the target is: 58
For input tensor: tensor([56,  6,  0, 24, 43, 58]), the target is: 1
For input tensor: tensor([56,  6,  0, 24, 43, 58,  1]), the target is: 61
For input tensor: tensor([56,  6,  0, 24, 43, 58,  1, 61]), the target is: 46
-----
For input tensor: tensor([39]), the target is: 47
For input tensor: tensor([39, 47]), the target is: 51
For input tensor: tensor([39, 47, 51]), the target is: 1
For input tensor: tensor([39, 47, 51,  1]), the target is: 58
For input tensor: tensor([39, 47, 51,  1, 58]), the target is: 46
For input tensor: tensor([39, 47, 51,  1, 58, 46]), the target is: 39
For input tensor: tensor([39, 47, 51,  1, 58, 46, 39]), the target is: 58
For input tensor: tensor([39, 47, 51,  1, 58, 46, 39

## 3. Building the B-Gram Langunage Model

As described before, this is a very simple language model. The target is to predict the next 1st word based on a given sequence.

In [10]:
class BigramLanguageModel(nn.Module):
    """ Bigram Language Model.
        Args:
            vocab_size (int): Number of tokens (size of vocabulary)
    """

    def __init__(self, vocab_size):
        super().__init__()
        # Each token directiry reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx) # B,T,C
        # cross_entropy expects the input (logits) to be of shape (B, C, T)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B*T, C),  targets.view(B*T))

        return logits ,loss

    def generate(self, idx, max_new_tokens):
        """ Generate new tokens, given current context.
            In a simple B-gram model, we just need to look up the logits for the next token.
            In more complex models, we are also intrested in the history of the tokens. In other
            words, a larger context.

            Args:
                idx (Tensor): Initial context
                max_new_tokens (int): Maximum number of new tokens to generate.
            Returns:
                Tensor: Generated tokens

        """

        # idx is a tensor of shape (B, T)
        idx.to(device)
        for i in range(max_new_tokens):
            # get the prediction for the current context
            logits, loss = self.forward(idx) # logits shape B, T, C
            # In B-gram model, focus only on the last time step.
            logits = logits[:, -1, :]   
            # convert logits to probabilities
            probs = F.softmax(logits, dim=-1)
            # sample the next token from the distribution
            next_token = torch.multinomial(probs, num_samples=1).to(device)
            idx = torch.cat([idx, next_token], dim=1) # shape B, T+1

        return idx
            
            


model = BigramLanguageModel(vocab_size)
model.to(device)
out, loss = model(xb, yb)
print(out.shape)
print(loss)

# We expect the loss to be around -log(1/vocab_size) = -log(1/65) = 4.17
print(f"Expected loss for uniform distribution: {-torch.log(torch.tensor(1/vocab_size))}")

# Example - generate new tokens
print("\n")
print("Example - generate new tokens")
print("(Model is not trained yet, so it will generate random tokens)")
idx = torch.zeros((1,1), dtype=torch.long).to(device)
new_tokens = model.generate(idx, 100)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)


torch.Size([4, 8, 65])
tensor(4.4609, grad_fn=<NllLossBackward0>)
Expected loss for uniform distribution: 4.174387454986572


Example - generate new tokens
(Model is not trained yet, so it will generate random tokens)

l-QYjt'CL?jLDuQcLzy'RIo;'KdhpV
vLixa,nswYZwLEPS'ptIZqOZJ$CA$zy-QTkeMk x.gQSFCLg!iW3fO!3DGXAqTsq3pdgq


### 3.1 Training the B-Gram Model
Without training the model, the results are random. The loss is roughly `-ln(1/vocab_size)`. To improve the model, we will train it with `AdamW` optimizer, and implement a simple training loop. 

In [11]:
# define the optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

The code block below, is used to estimate the loss. Instead of logging the loss of every epoch - which is very noisy, it will average the loss over `eval_iters` epochs. We shall run this block on both training and validation data. While training, it is important to see that the training and validation loss are decreasing. If the validation loss is increasing, it is a sign of overfitting.

In [12]:
eval_iters = 200
@torch.no_grad()
def estimate_loss():
    # estimate the loss on training and validation sets
    out = {}
    losses = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters).to(device)
        for k in range(eval_iters):
            xb, yb = get_batch(split)
            logits, loss = model(xb, yb)
            losses[k] = loss.item()
        out[split] = losses.mean().item()
    model.train()
    return out
        

In [13]:
# define the training loop
num_epochs = 10000
batch_size = 32
eval_interval = 100

model = model.to(device)
for step in range(num_epochs):
    
    if step % eval_interval == 0:
        losses = estimate_loss()
        print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

    # sample a batch of data
    xb, yb = get_batch(split="train")
    # forward pass
    logits, loss = model(xb, yb)

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

print(f"Loss = {loss.item()}") # this prints the loss of the last batch

Step: 0, Train Loss: 4.635080337524414, Val Loss: 4.645778656005859
Step: 100, Train Loss: 4.517083644866943, Val Loss: 4.5349040031433105
Step: 200, Train Loss: 4.418772220611572, Val Loss: 4.426044940948486
Step: 300, Train Loss: 4.308123588562012, Val Loss: 4.3238372802734375
Step: 400, Train Loss: 4.209145545959473, Val Loss: 4.215800762176514
Step: 500, Train Loss: 4.1152520179748535, Val Loss: 4.1276350021362305
Step: 600, Train Loss: 4.03169059753418, Val Loss: 4.0318074226379395
Step: 700, Train Loss: 3.9412500858306885, Val Loss: 3.950608015060425
Step: 800, Train Loss: 3.849108934402466, Val Loss: 3.866924524307251
Step: 900, Train Loss: 3.7737972736358643, Val Loss: 3.7728090286254883
Step: 1000, Train Loss: 3.695526123046875, Val Loss: 3.7079856395721436
Step: 1100, Train Loss: 3.6236352920532227, Val Loss: 3.636014699935913
Step: 1200, Train Loss: 3.548992872238159, Val Loss: 3.570427894592285
Step: 1300, Train Loss: 3.486809730529785, Val Loss: 3.5061960220336914
Step: 14

### 3.2. Generating Text From Trained B-Gram Model

In [14]:
idx = torch.zeros((1,1), dtype=torch.long, device=device)
new_tokens = model.generate(idx, 500)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)


Oryog ARKEve tou aroY:

Wanthintis n Thimed;
Hou f l ait ckin by mapa, owis.
Andean she dva
Agtut:

An t br'rtrercad locheres.
I oly I t onddocint biss be ceed vemmy I ngowhinothabld
tat hel I ompatyor yo t.
IIORIDe s, ir Bewilf sof ate k suser s y usprgr!
TUKiler igerindsolle CESIOFormegine s f pr'my.
US: ghiele.
ORe man thethes smm mu hen ffang pend.

CELENorfqve.
Whivingr ny atTheerklour, ad, othendete t rea'
LYo w? hor landinthes s h anofok, y thupe s celd
ul ayoe imovitod ane'l,
G st youo o


Now, looking at the result, we can see that the model has learned to generate text that looks like Shakespeare. However, the result is of low quality. This is because model is still quite simple and can be improved. To improve the model, we would like to learn the inter-relations between tokens in the sentence, even if they are far apart. This is where the **transformer** model comes in.

## 4. Building the Transformer Model
Up until now, using only the `Bigram Language Model`, we could not learn the inter relations between tokens. To predict the next token, we only used the previous token. **The transformer model, on the other hand, can learn the inter-relations between tokens, even if they are far apart.**

### 4.1 The Attention Module - Learning the Relations Between Tokens

In a language model, we would like to predict the next token, based only of preivous (context) tokens. This is different from models used for images, where we would like to learn the inter relations between one token, and the entire set of tokens representing the image.

The attention module, which is the at the core of the transformer model, is the building block used to learn and represent the inter-relations between tokens. When the attention module is applied to a sequence of tokens coming from the same input sequence of tokens, it is called **self-attention**. When the attention module is applied to two different sequences of tokens, it is called **cross-attention**. 


### 4.2 Preliminaries - Represting the Information of Previous Tokens as Average
As a first step, we would like to develop a method to represent the information of previous tokens. The most simple way to do that, would be to average the embeddings of all previous tokens.

Lets look a the next toy example:
Lets say our `batch` size is `4`, our `block_size` is `8`, and out `vocab_size` is 2.

In [15]:
import torch
torch.manual_seed(1337)
B,T,C = 4,8,2 #batch size, time, channels

x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [16]:
# We want to create a new tensor, where each element in the T dimension,
# is the mean of all elements before it:
# x[b,t] = mean_{i<=t} x[b,i]

xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]
        xbow[b,t] = torch.mean(xprev, 0)

print(x[0])
print(xbow[0])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])


#### 4.2.1 A Mathematical Trick

Although the above method outputs the desired averaging, because it uses `for` loops, it is very inefficient. To improve the efficency, we will use matrix multiplication.

A multipication of every matrix with a square matrix of size `nxn`, filled with `1, results in the summation of the rows.

So given the matrices:

In [17]:
a = torch.ones(3,3)
b = torch.randint(0,10, (3,2)).float()

print('a=')
print(a)
print('b=')
print(b)

a=
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
b=
tensor([[8., 6.],
        [5., 2.],
        [4., 4.]])


The running sum of the rows of `b` is given by:

In [18]:
c = a@b
print('c=')
print(c)

c=
tensor([[17., 12.],
        [17., 12.],
        [17., 12.]])


Now, because matrix `a` if a full mask of `1`, the result of all the rows in `c` is the same (we sum all rows in `b`).
If instead, matrix `a` will be a lower triangular matrix:

In [19]:
tril = torch.tril(torch.ones(3,3))
print(tril)

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])


Every element in `c` will be the sum of all previous elements in the same column in `b`:

In [20]:
c = tril@b
print('c=')
print(c)

c=
tensor([[ 8.,  6.],
        [13.,  8.],
        [17., 12.]])


Finally, becuase we want to average all the preivous elements, we can normalize matrix `a`, so that the sum of each row is `1`

In [21]:
tril = torch.tril(torch.ones(3,3))
a = tril / torch.sum(tril, dim=1, keepdim=True)
print('a=')
print(a)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])


So now, multiplying `a` by `b` will give us the desired result:

In [22]:
print('b=')
print(b)

c = a@b
print('c=')
print(c)

b=
tensor([[8., 6.],
        [5., 2.],
        [4., 4.]])
c=
tensor([[8.0000, 6.0000],
        [6.5000, 4.0000],
        [5.6667, 4.0000]])


Returning to the original `xbow`, whith size `(B,T,C)`, we would like to do the same trick, with batch multiplcation. 
So, if we have a tensor of size `(T,T)` and we multiply it by a tensor of size `(B,T,C)`, pytorch will autmalically broadcast the first tensor to size `(B,T,T)`, and multiply it by the second tensor.

`(B,T,T) x (B,T,C) = (B,T,C)`

In [23]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei@x

print ("xbow and xbow are the same. For example")
print("xbow[0,:3] ")
print(xbow[0,:3])
print("xbow2[0,:3] ")
print(xbow2[0,:3])


xbow and xbow are the same. For example
xbow[0,:3] 
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199]])
xbow2[0,:3] 
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199]])


#### 4.2.2. Using Softmax
When we train self attension module, we would like the weights to be learned. Thats because not every token will be equally important. So instead of using averaging, we are going to use `softmax` normalization.

We start by initializing all of our weights to `0`.

In [24]:
wei2 = torch.zeros(T, T)
wei2

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

Because we want to aggerate only past information, we will set all future elements to `-inf`. This will make the softmax of all future elements to `0`.

In [25]:
tril = torch.tril(torch.ones(T, T))
wei2 = wei2.masked_fill(tril==0, float('-inf'))
wei2

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

Now we are going to apply softmax function, and we will get the desired result.

In [26]:
wei2 = F.softmax(wei2, dim=1)
wei2

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

And the new `xbow` will be:

In [27]:
xbow3 = wei2@x
print("Are xbow2 and xbow3 the same: ", torch.allclose(xbow2, xbow3))

Are xbow2 and xbow3 the same:  True


### 5. Building the Self-Attention Block
In the above section, represented the information stored in previous tokens as an average of their embeddings. As seen from `xbow` matrices, this causes the embeddings to have similar weight. 
Instead, we need each of the embedding to have a different weight based on the current embedding. For example, if the current embedding is a noun, we would like the weights of the other embeddings to be higher if they are verbs, and lower if they are adjectives.

To do this, we propose two more vectors. The `query` vector `Q`, and the `key` vector `K`. 
Given the current token, the `Q` vector represents `what am I looking for`. The `K` vector represents `what do I have`. 
Analogous to the noun example, if the current token is a noun, the `Q` vector will have high weights where it expects verbs to be, and low weights where it expects adjectives to be. The `K` vector will have high weights where verbs are, and low weights where adjectives are.

`Q` and `K` are learnable vectors. 

In [28]:
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)

x = torch.randn(B, T, C)

k = key(x)  #(B,T,16)
q = query(x) #(B,T,16)

wei = q@k.transpose(-2, -1) # (B,T,16) @ (B,16,T) --> (B, T, T)

wei[0]

tensor([[ 0.5092,  0.8633, -0.0858, -0.2769,  0.2295, -0.2686, -0.4146, -0.7440],
        [-0.2630,  1.1151,  0.3556, -0.2197,  0.8090, -0.3172, -0.3451,  0.3032],
        [-0.3104, -0.2149,  0.1144,  0.0964,  0.0451,  0.0728,  0.1412,  0.4374],
        [-0.0152, -0.3885, -0.0698,  0.0925, -0.2224,  0.1140,  0.1423,  0.0410],
        [-0.4398,  0.1820,  0.2591,  0.0236,  0.3530, -0.0390,  0.0257,  0.5944],
        [ 0.0604, -0.3536, -0.1011,  0.0731, -0.2437,  0.1013,  0.1142, -0.0645],
        [-0.0111, -0.5781, -0.1097,  0.1360, -0.3373,  0.1692,  0.2094,  0.0453],
        [-0.6855, -1.2433,  0.0993,  0.3916, -0.3571,  0.3853,  0.5872,  1.0059]],
       grad_fn=<SelectBackward0>)

Now, because we don't want to aggeragate any information from future tokens, we are going to use the same trick as before - use a lower triangular matrix and set all future elements to `-inf`.

In [29]:
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril==0, float('-inf'))
wei = F.softmax(wei, dim=-1)
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2013, 0.7987, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2755, 0.3031, 0.4213, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2667, 0.1836, 0.2526, 0.2971, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1153, 0.2147, 0.2319, 0.1833, 0.2548, 0.0000, 0.0000, 0.0000],
        [0.1885, 0.1246, 0.1604, 0.1909, 0.1391, 0.1964, 0.0000, 0.0000],
        [0.1471, 0.0834, 0.1333, 0.1704, 0.1062, 0.1762, 0.1834, 0.0000],
        [0.0500, 0.0286, 0.1096, 0.1468, 0.0694, 0.1459, 0.1785, 0.2713]],
       grad_fn=<SelectBackward0>)

The last thing we need to do is to multiply the weights with the value `V` of the current token - also a learnable vector - and normalize with the size of the embedding.
The normalization is important to keep the variance of a normal distribution to be `1`, so that the weights don't become one hot vectors.

In [30]:
value = nn.Linear(C, head_size, bias=False)
v = value(x) #(B,T,16)

tril = torch.tril(torch.ones(T, T))
wei = head_size**(-0.5)*wei.masked_fill(tril==0, float('-inf'))
wei = F.softmax(wei, dim=-1)

out = wei@v
v[0]

tensor([[ 0.8914, -0.4325,  1.1267, -0.4434,  1.1065,  0.1209,  0.5062,  0.6908,
          0.4730,  0.3906, -0.4074,  0.9151, -1.0772, -0.4376, -0.7330,  0.5257],
        [-0.5965, -0.8033, -0.6086,  0.5651,  0.1012, -0.5463, -0.6486, -0.2655,
          0.1886, -0.5214,  0.1652,  0.6625,  0.6457, -0.1876, -0.5637, -0.1674],
        [-0.5705,  0.0589, -0.6921,  0.3373, -0.5403, -0.1702, -0.3857, -0.4029,
         -0.2020, -0.3019,  0.2393, -0.3314,  0.6744,  0.1842,  0.2589, -0.2997],
        [ 0.0050,  0.2514, -0.0274, -0.0649, -0.1893,  0.1088,  0.0749, -0.0418,
         -0.1147,  0.0626,  0.0227, -0.2910,  0.0114,  0.1092,  0.2408, -0.0399],
        [-0.8507, -0.2366, -0.9889,  0.5827, -0.5559, -0.3919, -0.6672, -0.5424,
         -0.1512, -0.5273,  0.3250, -0.1158,  0.9834,  0.1321,  0.0731, -0.3922],
        [ 0.1455,  0.2486,  0.1414, -0.1508, -0.0653,  0.1557,  0.1731,  0.0553,
         -0.0704,  0.1397, -0.0351, -0.2231, -0.1538,  0.0689,  0.1883,  0.0319],
        [ 0.0293,  0.3

#### **So, finally here is the attention module:**

In [75]:
class SelfAttentionHead(nn.Module):
    """One head of self attention"""

    def __init__(self, n_embd, head_size, block_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
    
    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        v = self.value(x)
        
        wei= q @ k.transpose(-2, -1) * C**(-0.5)
        wei = wei.masked_fill(self.tril[:T, :T]==0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        
        out = wei @ v
        return out

### 6. Integrating the Self-Attention Module into the Bigram Language Model
Now, lets add the self-attention module to the bigram model, so that it will learn the inter-relations between tokens. 
To do this, we first reduce the number of embeddings in the token embedding layer, and instead add a linear layer after the embedding layer. This will allow the model to learn more complex patterns in the data and increase stability.

Second, we add a positional encoding to the input embeddings. This is important because it helps the model learn the relations between tokens also based on their position in the sequence.

In [89]:
class BigramLanguageModelSignleAttention(nn.Module):
    """ Bigram Language Model.
        Args:
            vocab_size (int): Number of tokens (size of vocabulary)
    """
 
    def __init__(self, vocab_size, n_embd=24):
        super().__init__()
        # Each token directiry reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.pos_embedding_table = nn.Embedding(block_size, n_embd)
        self.atten_head = SelfAttentionHead(n_embd, head_size=16, block_size=block_size)
        self.head = nn.Linear(head_size, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        token_embd = self.token_embedding_table(idx) # (B,T,n_embd)
        pos_embd = self.pos_embedding_table(torch.arange(T).to(device)) # (T,n_embd)
        x = token_embd + pos_embd   # adding positional embedding to token embedding
        x = self.atten_head(x) # apply one head of attention
        logits = self.head(x) # (B,T,vocab_size)
        # cross_entropy expects the input (logits) to be of shape (B, C, T)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B*T, C),  targets.view(B*T))

        return logits ,loss

    def generate(self, idx, max_new_tokens):
        """ Generate new tokens, given current context.
            In a simple B-gram model, we just need to look up the logits for the next token.
            In more complex models, we are also intrested in the history of the tokens. In other
            words, a larger context.

            Args:
                idx (Tensor): Initial context
                max_new_tokens (int): Maximum number of new tokens to generate.
            Returns:
                Tensor: Generated tokens

        """

        # idx is a tensor of shape (B, T)
        idx.to(device)
        for i in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # only consider the last block_size tokens
            # get the prediction for the current context
            logits, loss = self.forward(idx_cond) # logits shape B, T, C
            # In B-gram model, focus only on the last time step.
            logits = logits[:, -1, :]   
            # convert logits to probabilities
            probs = F.softmax(logits, dim=-1)
            # sample the next token from the distribution
            next_token = torch.multinomial(probs, num_samples=1).to(device)
            idx = torch.cat([idx, next_token], dim=1) # shape B, T+1

        return idx
            
            


model = BigramLanguageModelSignleAttention(vocab_size)
model.to(device)
out, loss = model(xb, yb)
print(out.shape)
print(loss)

# We expect the loss to be around -log(1/vocab_size) = -log(1/65) = 4.17
print(f"Expected loss for uniform distribution: {-torch.log(torch.tensor(1/vocab_size))}")

# Example - generate new tokens
print("\n")
print("Example - generate new tokens")
print("(Model is not trained yet, so it will generate random tokens)")
idx = torch.zeros((1,1), dtype=torch.long).to(device)
new_tokens = model.generate(idx, 500)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)

torch.Size([32, 8, 65])
tensor(4.2162, grad_fn=<NllLossBackward0>)
Expected loss for uniform distribution: 4.174387454986572


Example - generate new tokens
(Model is not trained yet, so it will generate random tokens)

G3 yKKaJ:OFP3 myihe;mKE?XsGSKW!hbjaCSQ!'DZHn:xDHSuNYfP
kZHBbNk$?MnXLoj,pFcn3AHu,u!G'v-W::3cDKHkfb;.VfZwhLnbuNcW$3Jz,&;Px?TdBF:PYCQ&-Lq'ZvtJ&G:!;EnRXVNpQZ$QAtyfbMfslt,yL;DDH ED3g'In:hTh;$PnPrUct:Squp-.IDX
?3,.HNXwce:3H3naRxRKWT$fXNMMepd.-Whi E:E?:umFaLxgzZ:QBWDXTwO,iy;
vfECZlw-BtVVwbfLImnghhSb?hRED
YOwc3LsPETowotLjeIP'Idh!ZxuZRS 
fc&?ohED.3$lpoO!-vwmvaFcfhiWNPbGro?
qLIMRQ'fZpqttSbd$3RRQhJCs;nRhlq!gLfKMy,RWJaecP!dyH?cDcg:exX
xa!gHEQ
-JDfeKiXylxltjxKYYxB-bBG-EYEqda$,
k3dwa;DjtIld!sPekz
yATdcMn?b'th


#### Training the Model

Lets see if the model has improved.

In [33]:
# define the training loop
num_epochs = 10000
batch_size = 32
eval_interval = 100
lr = 1e-3

model = BigramLanguageModelSignleAttention(vocab_size)
model = model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
for step in range(num_epochs):
    
    if step % eval_interval == 0:
        losses = estimate_loss()
        print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

    # sample a batch of data
    xb, yb = get_batch(split="train")
    # forward pass
    logits, loss = model(xb, yb)

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

losses = estimate_loss()
print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

Step: 0, Train Loss: 4.318869113922119, Val Loss: 4.316243648529053
Step: 100, Train Loss: 3.361433744430542, Val Loss: 3.4011871814727783
Step: 200, Train Loss: 3.1943845748901367, Val Loss: 3.22554087638855
Step: 300, Train Loss: 3.101339340209961, Val Loss: 3.1098291873931885
Step: 400, Train Loss: 3.005418300628662, Val Loss: 2.986083984375
Step: 500, Train Loss: 2.899444580078125, Val Loss: 2.897247076034546
Step: 600, Train Loss: 2.8042774200439453, Val Loss: 2.8046178817749023
Step: 700, Train Loss: 2.751274824142456, Val Loss: 2.746579170227051
Step: 800, Train Loss: 2.711836576461792, Val Loss: 2.707810878753662
Step: 900, Train Loss: 2.6862480640411377, Val Loss: 2.678891658782959
Step: 1000, Train Loss: 2.6427645683288574, Val Loss: 2.6360716819763184
Step: 1100, Train Loss: 2.6075620651245117, Val Loss: 2.610530138015747
Step: 1200, Train Loss: 2.5975911617279053, Val Loss: 2.584049701690674
Step: 1300, Train Loss: 2.5819640159606934, Val Loss: 2.5862700939178467
Step: 1400

Previously we got the following loss:

`Step: 9900, Train Loss: 2.461491346359253, Val Loss: 2.5023200511932373`

After training the model with the self attention block, we get the following loss:

`Step: 9900, Train Loss: 2.3991994857788086, Val Loss: 2.40938138961792`

So we got some improvement.

### 7. Further Improvement: Multi-Head Attention

A single attention head can only learn a single type of inter relations between tokens. To learn multiple types of inter-relations, we can use multiple attention heads in parallel. This is called `multi-head attention`.


![multi-head-attention](assets/images/gpt/attention_heads.png)

To create a multi-head attention model, all we have to do is to create multiple `Q`, `K`, and `V` vectors, and apply the self-attention module to each of them. Each of the single attention heads will be concatenated, and passed through a linear layer to reduce the dimensionality back to the original size. 

In [91]:
class MultiHeadAttention(nn.Module):
    """Multi-head self attention"""

    def __init__(self, n_heads, n_embd, head_size, block_size):
        super().__init__()        
        self.heads = nn.ModuleList([SelfAttentionHead(n_embd, head_size, block_size) for _ in range(n_heads)])
        
    def forward(self, x):
        out = torch.cat([head(x) for head in self.heads], dim=-1)
        return out

Now lets integrate the multi-head attention into our model.
The important thing to note is reduce the number of embeddings according to the number of heads, so once they are concatenated they will have the same size as the original embeddings.

In [92]:
class BigramLanguageModelMultiHeadAttention(nn.Module):
    """ Bigram Language Model.
        Args:
            vocab_size (int): Number of tokens (size of vocabulary)
    """
 
    def __init__(self, vocab_size, n_embd=32, n_heads=4):
        super().__init__()
        # Each token directiry reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.pos_embedding_table = nn.Embedding(block_size, n_embd)
        head_size = n_embd // n_heads
        self.multi_att_head = MultiHeadAttention(n_heads=n_heads, n_embd=n_embd, head_size=head_size, block_size=block_size)
        self.head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        token_embd = self.token_embedding_table(idx) # (B,T,n_embd)
        pos_embd = self.pos_embedding_table(torch.arange(T).to(device)) # (T,n_embd)
        x = token_embd + pos_embd   # adding positional embedding to token embedding
        x = self.multi_att_head(x) # apply one head of attention
        logits = self.head(x) # (B,T,vocab_size)
        # cross_entropy expects the input (logits) to be of shape (B, C, T)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B*T, C),  targets.view(B*T))

        return logits ,loss

    def generate(self, idx, max_new_tokens):
        """ Generate new tokens, given current context.
            In a simple B-gram model, we just need to look up the logits for the next token.
            In more complex models, we are also intrested in the history of the tokens. In other
            words, a larger context.

            Args:
                idx (Tensor): Initial context
                max_new_tokens (int): Maximum number of new tokens to generate.
            Returns:
                Tensor: Generated tokens

        """

        # idx is a tensor of shape (B, T)
        idx.to(device)
        for i in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # only consider the last block_size tokens
            # get the prediction for the current context
            logits, loss = self.forward(idx_cond) # logits shape B, T, C
            # In B-gram model, focus only on the last time step.
            logits = logits[:, -1, :]   
            # convert logits to probabilities
            probs = F.softmax(logits, dim=-1)
            # sample the next token from the distribution
            next_token = torch.multinomial(probs, num_samples=1).to(device)
            idx = torch.cat([idx, next_token], dim=1) # shape B, T+1

        return idx
            
            


model = BigramLanguageModelMultiHeadAttention(vocab_size)
model.to(device)
out, loss = model(xb, yb)
print(out.shape)
print(loss)

# We expect the loss to be around -log(1/vocab_size) = -log(1/65) = 4.17
print(f"Expected loss for uniform distribution: {-torch.log(torch.tensor(1/vocab_size))}")

# Example - generate new tokens
print("\n")
print("Example - generate new tokens")
print("(Model is not trained yet, so it will generate random tokens)")
idx = torch.zeros((1,1), dtype=torch.long).to(device)
new_tokens = model.generate(idx, 500)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)

torch.Size([32, 8, 65])
tensor(4.2748, grad_fn=<NllLossBackward0>)
Expected loss for uniform distribution: 4.174387454986572


Example - generate new tokens
(Model is not trained yet, so it will generate random tokens)

WQ.&B.SgDDG.pi?K3a-FIDcm,YJRpBprSNTgQzHbUiunYj$lUYwIBc.RtPR'RLG$bVXmqo!MtTriMwxps;?-FJWmF''Y;S!sdVBYlnpgJtJD3?dP$FYMWKeNDYX?&;-$tVD;&b'.WAXXThWLgdnbFNMeY$t BaHmCY?lA,UemzsQ.PD? KLaQ,
jC;DqXuqWIFgnet.OUJEViKh'F,!nM?xKTwaPwZDyqOQtHmzmYvkVyl:eom?-unESecKXUYVFTUINTyCe.qScM:?Rp'FlylepQ'SOb'rBgfd&UNF,NI3FHjGhCU,llrwo EX!mtNVHdOIT'D;IJinlkxBYIUjRb:EeClrBMmBBFl:xvWlzmOBY;:ewXcAsQwoHhonKWmhVXonytKf3vLS.cYVysJV?O
CSnKeiaLBTgGdoWgNmrAHvTcU,3iSW.$;WLz,!AZeMLR
;IN'hVkG$SeTn$Q,uCtKKhXk3QmlcToOvUmy?TaP&UL$j&-S


Now lets train the new model and see if we have any improvement.

In [95]:
# define the training loop
num_epochs = 10000
batch_size = 32
eval_interval = 100
lr = 1e-3

model = BigramLanguageModelMultiHeadAttention(vocab_size)
model = model.to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
for step in range(num_epochs):
    
    if step % eval_interval == 0:
        losses = estimate_loss()
        print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

    # sample a batch of data
    xb, yb = get_batch(split="train")
    # forward pass
    logits, loss = model(xb, yb)

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

losses = estimate_loss()
print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

Step: 0, Train Loss: 4.280439376831055, Val Loss: 4.277841091156006
Step: 100, Train Loss: 3.1830806732177734, Val Loss: 3.2208504676818848
Step: 200, Train Loss: 2.981065034866333, Val Loss: 2.9953842163085938
Step: 300, Train Loss: 2.835463523864746, Val Loss: 2.8346798419952393
Step: 400, Train Loss: 2.721287488937378, Val Loss: 2.7226738929748535
Step: 500, Train Loss: 2.6442534923553467, Val Loss: 2.648371696472168
Step: 600, Train Loss: 2.59602427482605, Val Loss: 2.592071771621704
Step: 700, Train Loss: 2.5589630603790283, Val Loss: 2.5626206398010254
Step: 800, Train Loss: 2.539506196975708, Val Loss: 2.5365712642669678
Step: 900, Train Loss: 2.5071821212768555, Val Loss: 2.4975595474243164
Step: 1000, Train Loss: 2.49436616897583, Val Loss: 2.4855751991271973
Step: 1100, Train Loss: 2.471787452697754, Val Loss: 2.467949390411377
Step: 1200, Train Loss: 2.468949556350708, Val Loss: 2.4682157039642334
Step: 1300, Train Loss: 2.4356682300567627, Val Loss: 2.432159185409546
Step: 

And we got further improvement:

`Step: 9999, Train Loss: 2.1877453327178955, Val Loss: 2.239150047302246`.

Lets generate some text and see what we got:

In [96]:
# Example - generate new tokens
idx = torch.zeros((1,1), dtype=torch.long).to(device)
new_tokens = model.generate(idx, 500)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)


He thage vireshe me he an ight innshy mord I that it making Efe,
Wouch thee moy lact weed her
Whaters berends, ratis mut is't on a koner is you tersthe whas on ipleles arom's
Ade aruter aye thy tho-t vis here to' tio os ne of mignce, my
Thyou agegme.

JUMENLONTHERIO:
Throu for nojay co shave loow thom his of this Pur Of Hea
us, will cand fous and you ut, cie.

LICHAMANUS:
Hom then yem:
You wes.
Hellost, my friese wallyoose
therk
eveve, wam,

I IV:
Whath wrearceallanto gow hat.

MENWARD:
A's wims


There is still room for improvement, but the model is already generating text with some correct english words (i.e: `he`, `I`, `that`,`making`, `here`)

### 8. The Transformer Model

Now, that we have implemented the multi-head attention module, we can build the transformer model. The strength of the transformer model is that it can learn the inter-relations between tokens, even if they are far apart and complex. 

Lets look at the transformer block, as described in the paper:

![transformer-model](assets/transformer_model.png)

We are now going to break down the transformer model into its components:

#### **Masked Multi-Head Attention**
This is the multi-head attention we have implemented before.

#### **Layer Normalization**
This is a normalization technique similar to batch normalization, but instead of normalizing over the batch dimension, we normalize over the sequence dimension. This is important because we want to keep the inter-relations in the same sequence, and keep the different sequences separate.

In pytorch we can use `nn.LayerNorm` to implement this.

*Note:* In contrast to the paper, it is now common to use layer normaliation in the input of the multi-head attention module, and not in the output.

#### **Skip Connections**
As our network gets deeper, the gradients can become very small, and the training can be very difficult. Skip connections are simply the addition of the input to the output of a layer. This allows the gradients to flow directly to the input of the layer, and at the same time also modify the weights of the layer.

#### **Feed Forward Network**
The feed forward network is a simple linear layer followed by non-linearity. This helps the model learn more complex patterns in the data.

#### **Projection Layer**
The projection layer is at the end of the transformer block, and is used to project the output of the transformer block back to the original size of the embeddings. It is also learnable.

#### **Dropout**
Dropout is a regularization technique used to prevent overfitting. It works by randomly setting a fraction of the input to zero. In pytorch we can use `nn.Dropout` to implement this.


Putting all of this together we get the transformer block:

In [97]:
class FeedForward(nn.Module):
    """A simple linear layer followed by a ReLU activation"""
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(0.2)
        )
        
    def forward(self, x):
        return self.net(x)

In [99]:
class TransformerBlock(nn.Module):
    """A single transformer block"""
    def __init__(self, n_embd, n_heads, block_size):
        super().__init__()
        head_size = n_embd // n_heads
        self.att = MultiHeadAttention(n_heads, n_embd, head_size, block_size)
        self.ffwd = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.att(self.ln1(x))   # layer norm and skip connection
        x = x + self.ffwd(self.ln2(x))  # layer norm and skip connection
        return x

Now lets build the BigramTransformer model, and train it.

In [102]:
class BigramLanguageModelTransformer(nn.Module):
    def __init__(self, vocab_size, n_embd=32, n_heads=4, n_blocks=4):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.pos_embedding_table = nn.Embedding(block_size, n_embd)
        self.block_list = nn.ModuleList([TransformerBlock(n_embd, n_heads, block_size) for _ in range(n_blocks)])
        self.blocks = nn.Sequential(*self.block_list)
        self.ln = nn.LayerNorm(n_embd)  # layer norm before the final head
        self.head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        token_embd = self.token_embedding_table(idx) # (B,T,n_embd)
        pos_embd = self.pos_embedding_table(torch.arange(T, device=device)) # (T,n_embd)

        x = token_embd + pos_embd   # adding positional embedding to token embedding
        x = self.blocks(x) # apply transformer blocks (B,T,n_embd)
        x = self.ln(x) # layer norm
        logits = self.head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B*T, C),  targets.view(B*T))

        return logits ,loss
    
    def generate(self, idx, max_new_tokens):
        """ Generate new tokens, given current context.
            In a simple B-gram model, we just need to look up the logits for the next token.
            In more complex models, we are also intrested in the history of the tokens. In other
            words, a larger context.

            Args:
                idx (Tensor): Initial context
                max_new_tokens (int): Maximum number of new tokens to generate.
            Returns:
                Tensor: Generated tokens

        """

        # idx is a tensor of shape (B, T)
        idx.to(device)
        for i in range(max_new_tokens):
            idx_cond = idx[:, -block_size:] # only consider the last block_size tokens
            # get the prediction for the current context
            logits, loss = self.forward(idx_cond) # logits shape B, T, C
            # In B-gram model, focus only on the last time step.
            logits = logits[:, -1, :]   
            # convert logits to probabilities
            probs = F.softmax(logits, dim=-1)
            # sample the next token from the distribution
            next_token = torch.multinomial(probs, num_samples=1).to(device)
            idx = torch.cat([idx, next_token], dim=1) # shape B, T+1

        return idx

Now lets update the hyperparameters and train the model.

In [104]:
# hyper parameters
num_epochs = 10000
batch_size = 32
n_embd = 32
eval_interval = 100
lr = 1e-3
n_heads = 4
n_transformer_blocks = 4

model = BigramLanguageModelTransformer(vocab_size, n_embd, n_heads, n_transformer_blocks)
model = model.to(device)

# pytorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)

# training loop
for step in range(num_epochs):
    
    if step % eval_interval == 0:
        losses = estimate_loss()
        print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

    # sample a batch of data
    xb, yb = get_batch(split="train")
    # forward pass
    logits, loss = model(xb, yb)

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

losses = estimate_loss()
print(f"Step: {step}, Train Loss: {losses['train']}, Val Loss: {losses['val']}")

Step: 0, Train Loss: 4.290696620941162, Val Loss: 4.296289443969727
Step: 100, Train Loss: 3.0215697288513184, Val Loss: 3.0487074851989746
Step: 200, Train Loss: 2.66170597076416, Val Loss: 2.668571710586548
Step: 300, Train Loss: 2.531599521636963, Val Loss: 2.5354340076446533
Step: 400, Train Loss: 2.4548087120056152, Val Loss: 2.449009418487549
Step: 500, Train Loss: 2.4086432456970215, Val Loss: 2.40623140335083
Step: 600, Train Loss: 2.3734657764434814, Val Loss: 2.37636661529541
Step: 700, Train Loss: 2.342966079711914, Val Loss: 2.34257173538208
Step: 800, Train Loss: 2.327794075012207, Val Loss: 2.3352389335632324
Step: 900, Train Loss: 2.3091390132904053, Val Loss: 2.333873987197876
Step: 1000, Train Loss: 2.2615866661071777, Val Loss: 2.2774815559387207
Step: 1100, Train Loss: 2.2580363750457764, Val Loss: 2.2655227184295654
Step: 1200, Train Loss: 2.2333953380584717, Val Loss: 2.2473042011260986
Step: 1300, Train Loss: 2.2223074436187744, Val Loss: 2.2426459789276123
Step: 

We got further improvement, and the loss dropped to:

`Step: 9999, Train Loss: 1.8907207250595093, Val Loss: 2.0092897415161133`

Lets generate some text and see what we got:

In [105]:
# generate text from the model
context = torch.zeros((1,1), dtype=torch.long).to(device)
new_tokens = model.generate(context, 500)[0].tolist()

# decode the generated tokens
gen_txt = decode(new_tokens)
print(gen_txt)


Sit unwhs-as of ungenizee to belife mises
At draws by troplince, glood;
geill ave eveen
I gracly bit
recommentated,
Breenness: and to villoumply,
I to prick'd, a should despirs.
Telld; bark'?

Seconace.
That with him for to like displelease I wrest again,
The shall on the beid I brotitus:
Thhou go that het good thus
The postas?

Fit;
Will aid that deport the grough
Beg the Cevery copders!

BRIONGHARET:
Thy, but age!

MENENY Mise or beeen is and him wash Purpt must my wex tried his how theseth sw


This looks much better. The words look a lot more like english words, and the model has learned to generate text that looks like Shakespeare.
This not perfect, but it is a good result for a simple transformer model.
